updated the terms.json file
Olanetsoft/web3terms pull request #55
Opened 2022-10-03 12:45 UTC by 0xTife

2022-10-03 13:47 UTC, Qudusayo requested changes
- FUD and REKT already exist in the terms, You should update them instead
https://github.com/Olanetsoft/web3terms/blob/48ef57a0c805f1c15777e065614ca5945813bc6c/data/terms.json#L355-L356
https://github.com/Olanetsoft/web3terms/blob/48ef57a0c805f1c15777e065614ca5945813bc6c/data/terms.json#L603-L604

- You missed out on sorting the terms [as mentioned here](https://github.com/Olanetsoft/web3terms#-after-making-a-change) before making a PR.

2022-10-04 18:07 UTC, Olanetsoft approved these changes

2022-10-04 18:07 UTC, Olanetsoft commented on data/terms.json
> +    "term": "Hash Rate",
This should be in lower case

2022-10-04 18:07 UTC, Olanetsoft commented on data/terms.json
> +    "meaning": "Measurement of performance that reveals how many hashes per second your computer is capable of producing. Each hash is an attempt to find a block by creating a unique block candidate
Ensure this does not exceed 279 characters

2022-10-04 18:08 UTC, Olanetsoft commented
@gbolame Please respond to feedback; let's close this! Thank you

2022-10-05 15:43 UTC, closed without merging